# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeChallenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='desc',
            field=models.TextField(default='', max_length=255, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 16, 10, 49, 45, 605575)),
        ),
    ]
